### ISSUE TITLE
可以介绍下cfglock吗?

### ISSUE THREAD

**Issue by jqtmviyu** [SunSeekerX/intel-nuc8-i5beh-hackintosh-opencore-efi#2]
搜了下, "直接使用macOS的原生电源管理, 例如更完美的睡眠和CPU变频"

是需要对bios进行设置吗? 或者特定的版本?
我实际选择后似乎是提示没有找到.提示太快, 看不清命令输出就结束了.
如果不设置会影响正常使用吗?

(ps: args 可以考虑把-v去掉, 普通用户非调试应该不需要)

**Comment by SunSeekerX** [comment]
> 搜了下, "直接使用macOS的原生电源管理, 例如更完美的睡眠和CPU变频"
> 
> 是需要对bios进行设置吗? 或者特定的版本? 我实际选择后似乎是提示没有找到.提示太快, 看不清命令输出就结束了. 如果不设置会影响正常使用吗?
> 
> (ps: args 可以考虑把-v去掉, 普通用户非调试应该不需要)

好的，因为更新的是我本地文件，我本地打开了 -v，cfg 不需要对 bios 进行什么设置 nuc8 没有 cfglock
